name: Prettier
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actionsx/prettier@v2
        with:
          args: "--single-quote --trailing-comma all --prose-wrap always --write README.md"
