name: Run Prettier
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run prettier
        uses: actionsx/prettier@v2
        with:
          args: --single-quote --trailing-comma all --prose-wrap always --write README.md
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Apply formatting changes
